from django.urls import path
from . import views

urlpatterns = [
            path('', views.allblogs, name='sandbox'),
            path('2_2_basic_typography.html', views.allblogs, name='2_2_basic_typographyandbox'),
            path('2_3_text_alignment_display.html', views.allblogs, name='2_3_text_alignment_display'),
            path('2_4_floats_position.html', views.allblogs, name='2_4_floats_position'),
            path('2_4_floats_position.html', views.allblogs, name='2_4_floats_positionox'),
            path('2_5_colors_background.html', views.allblogs, name='2_5_colors_background'),
            path('2_6_spacing.html', views.allblogs, name='2_6_spacing'),
            path('2_7_sizing.html', views.allblogs, name='2_7_sizing'),
            path('2_7_sizing.html', views.allblogs, name=''),
            path('2_8_breakpoints.html', views.allblogs, name=''),
            path('3_2_buttons.html', views.allblogs, name=''),
            path('3_3_navbar.html', views.allblogs, name=''),
            path('3_4_list_groups_badges.html', views.allblogs, name=''),
            path('3_5_forms.html', views.allblogs, name=''),
            path('3_6_input_groups.html', views.allblogs, name=''),
            path('3_7_alerts_progress.html', views.allblogs, name=''),
            path('3_8_tables_pagination.html', views.allblogs, name=''),
            path('3_9_cards.html', views.allblogs, name=''),
            path('3_10_media_object.html', views.allblogs, name=''),
            path('3_11_jumbotron.html', views.allblogs, name=''),
            path('4_2_grid_system.html', views.allblogs, name=''),
            path('4_3_grid_alignment.html', views.allblogs, name=''),
            path('4_4_flexbox.html', views.allblogs, name=''),
            path('4_5_auto_margins_wrapping_order.html', views.allblogs, name=''),
            path('5_2_carousel.html', views.allblogs, name=''),
            path('5_3_collapse.html', views.allblogs, name=''),
            path('5_4_tooltips.html', views.allblogs, name=''),
            path('5_5_popovers.html', views.allblogs, name=''),
            path('5_6_modals.html', views.allblogs, name=''),
            path('5_7_scrollspy.html', views.allblogs, name='')
]
