from django.urls import path
from . import views

urlpatterns = [
            path('', views.sandbox_page, name='sandbox'),
            path('2_2_basic_typography.html', views.sandbox_page, name=''),
            path('2_3_text_alignment_display.html', views.sandbox_page, name=''),
            path('2_4_floats_position.html', views.sandbox_page, name=''),
            path('2_4_floats_position.html', views.sandbox_page, name=''),
            path('2_5_colors_background.html', views.sandbox_page, name=''),
            path('2_6_spacing.html', views.sandbox_page, name=''),
            path('2_7_sizing.html', views.sandbox_page, name=''),
            path('2_7_sizing.html', views.sandbox_page, name=''),
            path('2_8_breakpoints.html', views.sandbox_page, name=''),
            path('3_2_buttons.html', views.sandbox_page, name=''),
            path('3_3_navbar.html', views.sandbox_page, name=''),
            path('3_4_list_groups_badges.html', views.sandbox_page, name=''),
            path('3_5_forms.html', views.sandbox_page, name=''),
            path('3_6_input_groups.html', views.sandbox_page, name=''),
            path('3_7_alerts_progress.html', views.sandbox_page, name=''),
            path('3_8_tables_pagination.html', views.sandbox_page, name=''),
            path('3_9_cards.html', views.sandbox_page, name=''),
            path('3_10_media_object.html', views.sandbox_page, name=''),
            path('3_11_jumbotron.html', views.sandbox_page, name=''),
            path('4_2_grid_system.html', views.sandbox_page, name=''),
            path('4_3_grid_alignment.html', views.sandbox_page, name=''),
            path('4_4_flexbox.html', views.sandbox_page, name=''),
            path('4_5_auto_margins_wrapping_order.html', views.sandbox_page, name=''),
            path('5_2_carousel.html', views.sandbox_page, name=''),
            path('5_3_collapse.html', views.sandbox_page, name=''),
            path('5_4_tooltips.html', views.sandbox_page, name=''),
            path('5_5_popovers.html', views.sandbox_page, name=''),
            path('5_6_modals.html', views.sandbox_page, name=''),
            path('5_7_scrollspy.html', views.sandbox_page, name='')
]
